# Generated by Django 5.2.14 on 2026-05-28 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активно"),
                            ("archived", "В архиве"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="accounts.studentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("participating", "Участвует"),
                            ("not_participating", "Не участвует"),
                            ("thinking", "Думает"),
                            ("unknown", "Не ответил"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "payment_share",
                    models.CharField(
                        choices=[
                            ("regular", "Обычная доля"),
                            ("no_alcohol", "Без алкоголя"),
                            ("individual", "Индивидуальная доля"),
                            ("exempt", "Освобожден от оплаты"),
                        ],
                        default="regular",
                        max_length=32,
                    ),
                ),
                (
                    "custom_share_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Optional fixed amount in KZT for individual share participants.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="accounts.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в событии",
                "verbose_name_plural": "Участие в событиях",
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["group", "status"], name="events_even_group_i_bd6625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_date"], name="events_even_event_d_2c2da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["event", "status"], name="events_part_event_i_dacdf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["event", "payment_share"], name="events_part_event_i_1345be_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_user_participation"
            ),
        ),
    ]
