# Generated by Django 5.2.14 on 2026-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="payment_holder",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Владелец Kaspi"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Номер Kaspi организатора"
            ),
        ),
    ]
