# Generated by Django 5.2.14 on 2026-05-28 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fundraising",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "target_amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("deadline", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активен"),
                            ("locked", "Закрыт для изменений"),
                            ("finished", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraisings",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сбор средств",
                "verbose_name_plural": "Сборы средств",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "common_amount",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "alcohol_amount",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "individual_amount",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("rounding_delta", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=120)),
                ("organizer_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fundraising",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="fundraising.fundraising",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="accounts.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счет",
                "verbose_name_plural": "Счета",
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_categories",
                        to="accounts.studentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("normalized_title", models.CharField(db_index=True, max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("unit", models.CharField(default="шт", max_length=32)),
                (
                    "unit_price",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("common", "Общий"),
                            ("alcohol", "Алкоголь"),
                            ("individual", "Индивидуальный"),
                            ("selected_group", "Для выбранной группы"),
                        ],
                        default="common",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Предложен"),
                            ("approved", "Утвержден"),
                            ("rejected", "Отклонен"),
                            ("purchased", "Куплен"),
                        ],
                        default="proposed",
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("store_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.telegramuser",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="fundraising.itemcategory",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="fundraising.priceitem",
                    ),
                ),
                (
                    "fundraising",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fundraising.fundraising",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар прайс-листа",
                "verbose_name_plural": "Товары прайс-листа",
            },
        ),
        migrations.CreateModel(
            name="PriceItemSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supports",
                        to="fundraising.priceitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supported_items",
                        to="accounts.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поддержка товара",
                "verbose_name_plural": "Поддержки товаров",
            },
        ),
        migrations.AddIndex(
            model_name="fundraising",
            index=models.Index(
                fields=["event", "status"], name="fundraising_event_i_765769_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fundraising",
            index=models.Index(
                fields=["deadline"], name="fundraising_deadlin_59ad32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["fundraising", "status"], name="fundraising_fundrai_b33e64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status"], name="fundraising_user_id_5e441b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("fundraising", "user"), name="unique_invoice_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.UniqueConstraint(
                fields=("group", "name"), name="unique_category_per_group"
            ),
        ),
        migrations.AddIndex(
            model_name="priceitem",
            index=models.Index(
                fields=["fundraising", "status"], name="fundraising_fundrai_38be90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceitem",
            index=models.Index(
                fields=["fundraising", "normalized_title"],
                name="fundraising_fundrai_a7c1c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="priceitem",
            index=models.Index(
                fields=["item_type"], name="fundraising_item_ty_2deacf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="priceitemsupport",
            constraint=models.UniqueConstraint(
                fields=("item", "user"), name="unique_item_support"
            ),
        ),
    ]
