# Generated by Django 5.2.14 on 2026-05-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
