# Generated by Django 5.2.14 on 2026-06-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentgroup_invite_code'),
        ('fundraising', '0004_priceitem_source_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='accounts.telegramuser'),
        ),
    ]
