# Generated by Django 5.2.14 on 2026-05-28 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=500)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                (
                    "estimated_price",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("rent_terms", models.TextField(blank=True)),
                ("pros", models.TextField(blank=True)),
                ("cons", models.TextField(blank=True)),
                ("author_comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Предложено"),
                            ("approved", "Утверждено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="proposed",
                        max_length=32,
                    ),
                ),
                (
                    "interest_color",
                    models.CharField(
                        choices=[
                            ("gray", "Серый"),
                            ("blue", "Синий"),
                            ("green", "Зеленый"),
                            ("yellow", "Желтый"),
                            ("red", "Красный"),
                        ],
                        default="blue",
                        max_length=16,
                    ),
                ),
                (
                    "interest_score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.telegramuser",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_ideas",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Идея места",
                "verbose_name_plural": "Идеи мест",
            },
        ),
        migrations.CreateModel(
            name="PlaceVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="places.placeidea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_votes",
                        to="accounts.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Голос за место",
                "verbose_name_plural": "Голоса за места",
            },
        ),
        migrations.AddIndex(
            model_name="placeidea",
            index=models.Index(
                fields=["event", "status"], name="places_plac_event_i_99d7fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placeidea",
            index=models.Index(
                fields=["event", "interest_color"],
                name="places_plac_event_i_862f0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="placeidea",
            index=models.Index(
                fields=["latitude", "longitude"], name="places_plac_latitud_925c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placevote",
            index=models.Index(
                fields=["place", "created_at"], name="places_plac_place_i_d0c2b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="placevote",
            constraint=models.UniqueConstraint(
                fields=("place", "user"), name="unique_place_vote"
            ),
        ),
    ]
