# Generated by Django 5.2.14 on 2026-05-28 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("telegram_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="KZT", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Группа студентов",
                "verbose_name_plural": "Группы студентов",
                "indexes": [
                    models.Index(
                        fields=["telegram_chat_id"],
                        name="accounts_st_telegra_b39cb4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("photo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Пользователь Telegram",
                "verbose_name_plural": "Пользователи Telegram",
                "indexes": [
                    models.Index(
                        fields=["telegram_id"], name="accounts_te_telegra_50ceb1_idx"
                    ),
                    models.Index(
                        fields=["username"], name="accounts_te_usernam_a26290_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("participant", "Участник"),
                            ("organizer", "Организатор"),
                            ("admin", "Администратор"),
                        ],
                        default="participant",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts.studentgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник группы",
                "verbose_name_plural": "Участники групп",
                "indexes": [
                    models.Index(
                        fields=["group", "role"], name="accounts_me_group_i_8f5b7b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "group"), name="unique_user_group_membership"
                    )
                ],
            },
        ),
    ]
